name: Cloudall Workers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install wrangler
        run: npm install -g wrangler@4.71.0
      - name: Check wrangler version
        run: npx --yes --no-install wrangler --version
